### PR TITLE
mdx-syntax-highlighting

### PR DESCRIPTION
**Pull request by ropats16**
Added mdx syntax highlighting

### CODE REVIEW

**Review by with-heart — APPROVED** [review]
We should create `components.img` to render `Image` from `next/image` to make sure we're getting image optimization.

imo you could just open an issue to track it and fix that later though

**Comment by briangershon** [comment]
I noticed bullets are missing on the final render. I assume we just need to support the `li` tag.

I'll work on adding this today.

**Review by briangershon — APPROVED** [review]

**Comment by ropats16** [comment]
> 

Hey @with-heart can you share some implementation example of the Next/Image being passed to the mdx img component? I tried setting it up but actually creates and issue because the layout or height and width are needed and it also throws the image out of the flow of content.

**Comment by briangershon** [comment]
Hey @ropats16 this seems to be working for me.

- I set a default width/height to be 100px since those properties are required.
- I think this also means we'll need to use the `` tags in MDX files and not the markdown versions, so that we can set width/height.

## Code changes

```diff
diff --git a/lessons/1.mdx b/lessons/1.mdx
index c92fb8d..9eb5a9d 100644
--- a/lessons/1.mdx
+++ b/lessons/1.mdx
@@ -24,6 +24,8 @@ In this project we are going to create a web3 fortune-teller.

 For this, we will write a smart contract, using the Solidity language.

+<img src="/assets/remix.png" width={200} height={200} />
+
 - **What is a Smart Contract?** (new - open for newer edits)
   ![Smart contract (new)](/assets/remix.png)
   Like a traditional contract, a **Smart Contract** is a set of data and custom rules, with the addition of pre-defined instructions, like a computer program, that can be executed when a user makes a transaction with them. These instructions can modify the data stored in the contract.
diff --git a/pages/lessons/[slug].tsx b/pages/lessons/[slug].tsx
index 53b9b45..0b44475 100644
--- a/pages/lessons/[slug].tsx
+++ b/pages/lessons/[slug].tsx
@@ -7,6 +7,7 @@ import matter from 'gray-matter'
 import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
 import dracula from 'react-syntax-highlighter/dist/cjs/styles/prism/dracula'
 import { useTranslation } from 'next-i18next'
+import Image from 'next/image';

 interface LessonProps {
   frontMatter: {
@@ -41,6 +42,7 @@ const components = {
   p: (props: any) => <Text as="p" apply="mdx.p" fontSize="xl" {...props} />,
   a: (props: any) => <Text as="a" apply="mdx.a" fontSize="xl" {...props} />,
   ul: (props: any) => <Text as="ul" apply="mdx.ul" fontSize="xl" {...props} />,
+  img: (props: any) => <Image width={100} height={100} {...props} />,
 }

 const Lesson: React.FC<LessonProps> = ({
```

**Comment by briangershon** [comment]
We'll need to create a guide for people creating content in MDX since adding images will be confusing:

- They'll need to use `` instead of markdown afaik
- If they do use markdown, they'll see images that are tiny (due to 100x100 default properties) so will be scratching their heads
- On a related note, maybe there should be no default size, so that errors do happen if author tries to add image without `height` or `width`

**Comment by briangershon** [comment]
Thanks @ropats16, the image/alt clean-up looks great.

Also I think going with Chakra `Image` may work out better since it's still easy for content editors to work with (since height/width not required).

**Pull request merged**
