### PR TITLE
Added next and previous lesson buttons. Add VSCode Container.

### LINKED ISSUE #71: Add navigation between lessons
Currently there is no way to navigate between lessons from each lesson page.

This issue is for adding forward and back navigation icons.

### PR DESCRIPTION
**Pull request by DanielOlarte**
Closes #71 

I also added the default setup to use VSCode Remote Containers (those files were generated automatically by VS).

I ran yarn confirm before submitting and it automatically updates those lesson files.

### CODE REVIEW

**Review by briangershon — CHANGES_REQUESTED** [review]
Thanks @DanielOlarte 

I reviewed your Docker Remote Container piece.

It looks good and works well -- my feedback is just adding a bit of documentation in README about this as a setup option, and I also had a question about `base.Dockerfile`

Details:

- [x] Could you add a link or bit of text in the README in `Project Setup` section to help new users take advantage of this option for running a project locally? They can do existing option, or the new container version. I also saw this cool feature I didn't know about that you might consider -- adding a Badge in the README: https://code.visualstudio.com/docs/remote/create-dev-container#_add-an-open-in-dev-container-badge
- [ ] Is the `base.Dockerfile` just a reference so people know what what the prebuilt one does that you're using in `Dockerfile`? If yes, I'm thinking you can probably remove to simplify and avoid any confusion for future users, since if someone really needs to know details, then can easily find. Or let me know if I'm misunderstanding too!

**Review by PBillingsby — APPROVED** [review]
LGTM. Good stuff @DanielOlarte. We can revisit the refactor of making this dynamic!

**Comment by DanielOlarte** [comment]
> Thanks @DanielOlarte
> 
> I reviewed your Docker Remote Container piece.
> 
> It looks good and works well -- my feedback is just adding a bit of documentation in README about this as a setup option, and I also had a question about `base.Dockerfile`
> 
> Details:
> 
> * [x]  Could you add a link or bit of text in the README in `Project Setup` section to help new users take advantage of this option for running a project locally? They can do existing option, or the new container version. I also saw this cool feature I didn't know about that you might consider -- adding a Badge in the README: https://code.visualstudio.com/docs/remote/create-dev-container#_add-an-open-in-dev-container-badge
> * [x]  Is the `base.Dockerfile` just a reference so people know what what the prebuilt one does that you're using in `Dockerfile`? If yes, I'm thinking you can probably remove to simplify and avoid any confusion for future users, since if someone really needs to know details, then can easily find. Or let me know if I'm misunderstanding too!

1) I added some documentation on the README about it, let me know if that's good enough. I checked the badges and they work well if we want the developers to create the container from the original repo, but, we are using forks then it doesn't seem to support that way to do it.
2) Based on the docs, the base.Dockerfile it's the actual "recipe" of the FROM image that is specified on the Dockerfile. Then, it is useful to leave it to have everyone share the same config no matter what.

Let me know if you have any questions!

**Review by briangershon — APPROVED** [review]
Thanks @DanielOlarte for updating the README re: containers.

**Pull request merged**
